---
name: cdn77-sync-action
description: |
  Action for uploading files to CDN77 storage + Google Cloud Storage, purging them via API and triggerin
inputs:
  source_path:
    description: The source path.
    required: true
  destination_path:
    description: The destination path.
    required: true
  cdn77_storage_host:
    description: The cdn77 storage hostname.
    required: true
  cdn77_storage_user:
    description: The cdn77 storage username.
    required: true
  cdn77_storage_private_key:
    description: A private key that secures communication to the remote storage.
    required: true
  gcs_bucket:
    description: The Google Cloud Storage bucket name.
    required: true
  cdn77_api_purge_limit:
    description: Max amount of files which should be sent per purge request.
    required: false
    default: '1750'
  cdn77_resource_id:
    description: The cdn77 resource id.
    required: true
  cdn77_api_token:
    description: The cdn77 api token.
    required: true
runs:
  using: docker
  image: Dockerfile