---
name: cdn77-sync-action
description: |
  Action for uploading files to CDN77 storage and purging them via API
inputs:
  source_path:
    description: The source path.
    required: true
  destination_path:
    description: The destination path.
    required: true
  cdn77_host:
    description: The cdn77 host.
    required: true
  cdn77_user:
    description: The cdn77 username.
    required: true
runs:
  using: docker
  image: Dockerfile